### ISSUE TITLE
Feedabck on upgrade

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/cats#4]
Step 2 - Adding the wait block to stop the blue dot works, as long as you stop the script each time. If you just hit the green flag again, to restart the script, it just draws a line to where the cursor is. Suggest that a `pen up` block is added before the wait.

Step 6 - Resetting the score to zero within the starts as clone script keeps the score at zero. I think it should be in the green flag script. I think the clone also needs to be deleted at this point - or the score keeps increasing

Otherwise all looks good

**Comment by lawsie** [comment]
Done both. Derp. Thanks!
